"use client";

/**
 * ─────────────────────────────────────────────────────────────────────────
 *  THE IMPORT WIZARD — four steps, and one honest preview.
 * ─────────────────────────────────────────────────────────────────────────
 *   1  File      pick a spreadsheet, or take the template first
 *   2  Columns   our columns beside theirs, pre-matched
 *   3  Settings  what happens to stock, and how prices are worked out
 *   4  Review    exactly what will be created, changed and blocked
 *
 * The rule the whole screen is built around: NOTHING IS WRITTEN UNTIL STEP
 * 4 IS APPROVED. Steps 1–3 are pure reads, so a seller can go back and
 * forth freely — and the preview is generated by the same code that does
 * the writing, so it cannot promise something the commit won't do.
 * ─────────────────────────────────────────────────────────────────────────
 */

import { useCallback, useMemo, useRef, useState, useTransition } from "react";
import Link from "next/link";
import {
  inspectUpload,
  previewImport,
  runImport,
  scanFileCategories,
  type PreviewPayload,
  type PreviewProduct,
} from "@/app/vendor/products/import/actions";
import type { CategoryScan, InspectResult } from "@/lib/import/pipeline";
import {
  IMPORT_FIELDS,
  mappingProblems,
  ROLE_LABELS,
  type ColumnMapping,
  type FieldKey,
  type FieldRole,
} from "@/lib/import/schema";
import { DEFAULT_PRICING, type RoundingMode } from "@/lib/import/pricing";
import type { StockMode } from "@/lib/import/plan";
import { money } from "@/lib/format";

interface CategoryOption {
  slug: string;
  name: string;
  depth: number;
}

interface Settings {
  rootSlug: string;
  mergeBasicLines: boolean;
  stockMode: StockMode;
  overwriteDetails: boolean;
  overwritePrices: boolean;
  publishImmediately: boolean;
  currency: string;
  fxRate: number;
  defaultMarkup: number;
  rounding: RoundingMode;
  markupByCategory: Record<string, number>;
}

const STEPS = ["File", "Columns", "Settings", "Review"] as const;

const ROLE_ORDER: FieldRole[] = ["identity", "variant", "commercial", "product", "reference"];

export default function ImportWizard({ categories }: { categories: CategoryOption[] }) {
  const fileRef = useRef<HTMLInputElement>(null);

  const [step, setStep] = useState(0);
  const [file, setFile] = useState<File | null>(null);
  const [inspection, setInspection] = useState<InspectResult | null>(null);
  const [sheetIndex, setSheetIndex] = useState(0);
  const [mapping, setMapping] = useState<ColumnMapping>({});
  const [preview, setPreview] = useState<PreviewPayload | null>(null);
  const [fileCategories, setFileCategories] = useState<CategoryScan[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();

  const [settings, setSettings] = useState<Settings>({
    rootSlug: "mens-fashion",
    mergeBasicLines: true,
    stockMode: "receive",
    overwriteDetails: false,
    overwritePrices: true,
    publishImmediately: false,
    currency: DEFAULT_PRICING.currency,
    fxRate: 1,
    defaultMarkup: DEFAULT_PRICING.defaultMarkup,
    rounding: DEFAULT_PRICING.rounding,
    // Empty, and filled from the file — see the scan on the way into
    // Settings. Seeding it from DEFAULT_MARKUPS put another catalogue's
    // categories in front of every seller.
    markupByCategory: {},
  });

  const [progress, setProgress] = useState<{
    processed: number;
    total: number;
    created: number;
    updated: number;
    skipped: number;
    failed: { name: string; reason: string }[];
    categories: string[];
    done: boolean;
  } | null>(null);

  const sheet = inspection?.sheets[sheetIndex];

  /** The payload every server action needs, rebuilt from current state. */
  const buildForm = useCallback((): FormData | null => {
    if (!file) return null;
    const form = new FormData();
    form.set("file", file);
    form.set(
      "settings",
      JSON.stringify({
        sheetIndex,
        mapping,
        rootSlug: settings.rootSlug,
        mergeBasicLines: settings.mergeBasicLines,
        stockMode: settings.stockMode,
        overwriteDetails: settings.overwriteDetails,
        overwritePrices: settings.overwritePrices,
        publishImmediately: settings.publishImmediately,
        pricing: {
          currency: settings.currency,
          fxRate: settings.fxRate,
          defaultMarkup: settings.defaultMarkup,
          markupByCategory: settings.markupByCategory,
          rounding: settings.rounding,
          compareAtUplift: 0,
        },
      }),
    );
    return form;
  }, [file, mapping, sheetIndex, settings]);

  // ── Step 1 → 2 ───────────────────────────────────────────────────
  function onFile(chosen: File | null) {
    setError(null);
    setPreview(null);
    setProgress(null);
    setFile(chosen);
    if (!chosen) return;

    const form = new FormData();
    form.set("file", chosen);

    startTransition(async () => {
      const response = await inspectUpload(form);
      if (!response.ok) {
        setError(response.error);
        setInspection(null);
        return;
      }
      setInspection(response.result);
      setSheetIndex(response.result.suggestedSheet);
      setMapping(response.result.suggestedMapping);
      if (response.result.suggestedRoot) {
        setSettings((s) => ({ ...s, rootSlug: response.result.suggestedRoot! }));
      }
      setStep(1);
    });
  }

  function chooseSheet(index: number) {
    setSheetIndex(index);
    // Each sheet has its own headers, so a mapping from the previous one is
    // meaningless — re-detect rather than carry over columns by position.
    setMapping({});
    setError(null);
  }

  /**
   * Step 2 → 3. The mapping is settled, so the file's own categories can
   * be resolved and offered for pricing.
   *
   * Suggested markups are applied only where a category MATCHES one we
   * have an opinion about — a store selling socks still gets 3.0 — and
   * anything already typed by hand is left alone, so coming back from the
   * review step does not discard the seller's numbers.
   */
  function loadCategories() {
    const form = buildForm();
    if (!form) return;
    setError(null);
    setStep(2);

    startTransition(async () => {
      const response = await scanFileCategories(form);
      if (!response.ok) {
        setError(response.error);
        return;
      }
      setFileCategories(response.categories);
      setSettings((s) => {
        const markups = { ...s.markupByCategory };
        for (const category of response.categories) {
          if (markups[category.slug] !== undefined) continue;
          const suggested = DEFAULT_PRICING.markupByCategory[category.slug];
          if (suggested !== undefined) markups[category.slug] = suggested;
        }
        return { ...s, markupByCategory: markups };
      });
    });
  }

  // ── Step 3 → 4 ───────────────────────────────────────────────────
  function loadPreview() {
    const form = buildForm();
    if (!form) return;
    setError(null);
    startTransition(async () => {
      const response = await previewImport(form);
      if (!response.ok) {
        setError(response.error);
        return;
      }
      setPreview(response.payload);
      setStep(3);
    });
  }

  // ── Commit ───────────────────────────────────────────────────────
  function commit() {
    if (!file || !preview) return;
    setError(null);

    startTransition(async () => {
      let offset = 0;
      const totals = {
        processed: 0,
        total: preview.stats.products,
        created: 0,
        updated: 0,
        skipped: 0,
        failed: [] as { name: string; reason: string }[],
        categories: [] as string[],
        done: false,
      };

      // Committed in batches so no single request runs long enough to be
      // cut off mid-catalogue, and so the seller watches it move.
      for (;;) {
        const batch = buildForm();
        if (!batch) return;
        batch.set("offset", String(offset));

        const response = await runImport(batch);
        if (!response.ok) {
          setError(response.error);
          setProgress({ ...totals });
          return;
        }

        totals.processed = response.processed;
        totals.created += response.created;
        totals.updated += response.updated;
        totals.skipped += response.skipped;
        totals.failed.push(...response.failed);
        totals.categories.push(...response.categoriesCreated);
        totals.done = response.done;
        setProgress({ ...totals });

        if (response.done) break;
        offset = response.processed;
      }
    });
  }

  const columnProblems = useMemo(() => mappingProblems(mapping), [mapping]);
  const canContinueFromColumns = columnProblems.length === 0;

  return (
    <div>
      <Steps current={step} />

      {error && (
        <p className="mt-4 rounded-xl bg-coral-100 px-4 py-3 text-sm text-coral-700" role="alert">
          {error}
        </p>
      )}

      {step === 0 && (
        <FileStep file={file} pending={pending} inputRef={fileRef} onFile={onFile} />
      )}

      {step === 1 && inspection && sheet && (
        <ColumnStep
          inspection={inspection}
          sheetIndex={sheetIndex}
          onSheet={chooseSheet}
          mapping={mapping}
          setMapping={setMapping}
          canContinue={canContinueFromColumns}
          problems={columnProblems}
          onBack={() => setStep(0)}
          onNext={loadCategories}
        />
      )}

      {step === 2 && (
        <SettingsStep
          settings={settings}
          setSettings={setSettings}
          categories={categories}
          fileCategories={fileCategories}
          pending={pending}
          onBack={() => setStep(1)}
          onNext={loadPreview}
        />
      )}

      {step === 3 && preview && (
        <ReviewStep
          preview={preview}
          settings={settings}
          progress={progress}
          pending={pending}
          onBack={() => setStep(2)}
          onCommit={commit}
        />
      )}
    </div>
  );
}

// ── Step chrome ────────────────────────────────────────────────────────

function Steps({ current }: { current: number }) {
  return (
    <ol className="flex flex-wrap items-center gap-2 text-sm">
      {STEPS.map((label, index) => {
        const state = index === current ? "current" : index < current ? "done" : "todo";
        return (
          <li key={label} className="flex items-center gap-2">
            <span
              className={
                "flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold " +
                (state === "current"
                  ? "bg-ocean-700 text-white"
                  : state === "done"
                    ? "bg-ocean-100 text-ocean-800"
                    : "bg-sand-100 text-slate-400")
              }
            >
              {state === "done" ? "✓" : index + 1}
            </span>
            <span
              className={
                state === "todo" ? "text-slate-400" : "font-medium text-ocean-950"
              }
            >
              {label}
            </span>
            {index < STEPS.length - 1 && <span className="mx-1 text-sand-200">—</span>}
          </li>
        );
      })}
    </ol>
  );
}

function Actions({
  onBack,
  onNext,
  nextLabel,
  disabled,
  pending,
}: {
  onBack?: () => void;
  onNext?: () => void;
  nextLabel: string;
  disabled?: boolean;
  pending?: boolean;
}) {
  return (
    <div className="mt-6 flex items-center justify-between gap-3">
      {onBack ? (
        <button type="button" onClick={onBack} className="btn-secondary !px-5 !py-2 text-sm">
          Back
        </button>
      ) : (
        <span />
      )}
      {onNext && (
        <button
          type="button"
          onClick={onNext}
          disabled={disabled || pending}
          className="btn-primary !px-5 !py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50"
        >
          {pending ? "Working…" : nextLabel}
        </button>
      )}
    </div>
  );
}

// ── Step 1: the file ───────────────────────────────────────────────────

function FileStep({
  file,
  pending,
  inputRef,
  onFile,
}: {
  file: File | null;
  pending: boolean;
  inputRef: React.RefObject<HTMLInputElement | null>;
  onFile: (file: File | null) => void;
}) {
  const [dragging, setDragging] = useState(false);

  return (
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]">
      <div className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">Upload your supplier file</h2>
        <p className="mt-1 text-sm text-slate-500">
          An Excel workbook (.xlsx) or a CSV. One row per colour and size — the
          same shape a purchase invoice or packing list already has.
        </p>

        <label
          onDragOver={(event) => {
            event.preventDefault();
            setDragging(true);
          }}
          onDragLeave={() => setDragging(false)}
          onDrop={(event) => {
            event.preventDefault();
            setDragging(false);
            onFile(event.dataTransfer.files?.[0] ?? null);
          }}
          className={
            "mt-5 flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed px-6 py-12 text-center transition " +
            (dragging ? "border-ocean-500 bg-ocean-50" : "border-sand-200 bg-sand-50 hover:border-ocean-300")
          }
        >
          <span className="text-4xl">📄</span>
          <span className="mt-3 font-semibold text-ocean-950">
            {file ? file.name : "Drop the file here, or click to choose"}
          </span>
          <span className="mt-1 text-xs text-slate-500">
            {file
              ? `${(file.size / 1024).toFixed(0)} KB — reading…`
              : ".xlsx or .csv, up to 15 MB"}
          </span>
          <input
            ref={inputRef}
            type="file"
            accept=".xlsx,.xlsm,.csv,.tsv,.txt"
            className="hidden"
            onChange={(event) => onFile(event.target.files?.[0] ?? null)}
          />
        </label>

        {pending && (
          <p className="mt-4 text-sm text-slate-500">Reading the file and matching columns…</p>
        )}
      </div>

      <div className="card bg-ocean-50/60 p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">
          Not sure of the format?
        </h2>
        <p className="mt-1 text-sm text-slate-600">
          Download the template. It has the columns we read, marked so you can
          see which three are required, and three filled-in example rows.
        </p>

        <a
          href="/api/import-template"
          download
          className="btn-secondary mt-4 !px-5 !py-2 text-sm"
        >
          ⬇ Download template (CSV)
        </a>

        <div className="mt-6 rounded-xl bg-white p-4 text-sm">
          <p className="font-semibold text-ocean-950">The one rule that matters</p>
          <p className="mt-1 text-slate-600">
            One row per <strong>colour and size</strong>, all sharing the same
            product code. That is how eleven rows become one shirt with eleven
            variants instead of eleven separate products.
          </p>
        </div>

        <p className="mt-4 text-xs text-slate-500">
          Your file does not have to match the template. On the next step you
          choose which of your columns feeds each of ours — we pre-match
          everything we recognise.
        </p>
      </div>
    </div>
  );
}

// ── Step 2: the column mapper ──────────────────────────────────────────

function ColumnStep({
  inspection,
  sheetIndex,
  onSheet,
  mapping,
  setMapping,
  canContinue,
  problems,
  onBack,
  onNext,
}: {
  inspection: InspectResult;
  sheetIndex: number;
  onSheet: (index: number) => void;
  mapping: ColumnMapping;
  setMapping: (mapping: ColumnMapping) => void;
  canContinue: boolean;
  problems: string[];
  onBack: () => void;
  onNext: () => void;
}) {
  const sheet = inspection.sheets[sheetIndex];

  /** Columns already claimed by another field, so one can't feed two. */
  const claimed = useMemo(() => {
    const byColumn = new Map<number, FieldKey>();
    for (const [key, column] of Object.entries(mapping) as [FieldKey, number][]) {
      if (column !== undefined) byColumn.set(column, key);
    }
    return byColumn;
  }, [mapping]);

  function assign(field: FieldKey, value: string) {
    const next = { ...mapping };
    if (value === "") {
      delete next[field];
    } else {
      const column = Number(value);
      // A column can only feed one field; taking it releases it elsewhere.
      const previousOwner = claimed.get(column);
      if (previousOwner && previousOwner !== field) delete next[previousOwner];
      next[field] = column;
    }
    setMapping(next);
  }

  const unmapped = sheet.headers
    .map((header, index) => ({ header, index }))
    .filter(({ index }) => !claimed.has(index));

  const matched = Object.keys(mapping).length;

  return (
    <div className="mt-6">
      <div className="card p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h2 className="font-display text-lg font-bold text-ocean-950">
              Match your columns to ours
            </h2>
            <p className="mt-1 text-sm text-slate-500">
              We recognised <strong>{matched}</strong> of {sheet.headers.length} columns
              in <strong>{sheet.name}</strong> ({sheet.rowCount.toLocaleString()} rows).
              Change anything that looks wrong.
            </p>
          </div>

          {inspection.sheets.length > 1 && (
            <label className="text-sm">
              <span className="label">Sheet</span>
              <select
                className="input !py-2"
                value={sheetIndex}
                onChange={(event) => onSheet(Number(event.target.value))}
              >
                {inspection.sheets.map((option) => (
                  <option key={option.index} value={option.index}>
                    {option.name} ({option.rowCount} rows)
                  </option>
                ))}
              </select>
            </label>
          )}
        </div>

        {!canContinue && (
          <div className="mt-4 rounded-xl bg-mango-50 px-4 py-3 text-sm text-mango-800">
            <p className="font-semibold">Still needed before you can continue:</p>
            <ul className="mt-1 list-disc space-y-0.5 pl-5">
              {problems.map((problem) => (
                <li key={problem}>{problem}</li>
              ))}
            </ul>
          </div>
        )}

        <div className="mt-6 space-y-8">
          {ROLE_ORDER.map((role) => {
            const fields = IMPORT_FIELDS.filter((field) => field.role === role);
            if (fields.length === 0) return null;

            return (
              <section key={role}>
                <h3 className="font-display text-sm font-bold uppercase tracking-wide text-ocean-700">
                  {ROLE_LABELS[role]}
                </h3>

                <div className="mt-3 grid gap-3 md:grid-cols-2">
                  {fields.map((field) => {
                    const column = mapping[field.key];
                    const samples =
                      column === undefined
                        ? []
                        : (sheet.samples[column] ?? []).filter(Boolean).slice(0, 3);

                    return (
                      <div
                        key={field.key}
                        className={
                          "rounded-xl border p-4 " +
                          (field.required && column === undefined
                            ? "border-coral-500/40 bg-coral-100/30"
                            : "border-sand-200 bg-white")
                        }
                      >
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-sm font-semibold text-ocean-950">
                            {field.label}
                          </span>
                          {field.required ? (
                            <span className="rounded-full bg-coral-500/10 px-2 py-0.5 text-[11px] font-bold uppercase text-coral-700">
                              Required
                            </span>
                          ) : (
                            <span className="text-[11px] text-slate-400">Optional</span>
                          )}
                        </div>

                        <p className="mt-1 text-xs leading-relaxed text-slate-500">
                          {field.hint}
                        </p>

                        <select
                          className="input mt-3 !py-2"
                          value={column === undefined ? "" : String(column)}
                          onChange={(event) => assign(field.key, event.target.value)}
                        >
                          <option value="">— not in my file —</option>
                          {sheet.headers.map((header, index) => (
                            <option key={index} value={index}>
                              {header}
                              {claimed.has(index) && claimed.get(index) !== field.key
                                ? "  (used above)"
                                : ""}
                            </option>
                          ))}
                        </select>

                        {samples.length > 0 && (
                          <p className="mt-2 truncate text-xs text-slate-400" title={samples.join(" · ")}>
                            e.g. {samples.join(" · ")}
                          </p>
                        )}
                        {field.odoo && (
                          <p className="mt-1 text-[11px] text-slate-400">→ Odoo {field.odoo}</p>
                        )}
                      </div>
                    );
                  })}
                </div>
              </section>
            );
          })}
        </div>

        {unmapped.length > 0 && (
          <div className="mt-8 rounded-xl bg-sand-50 p-4">
            <p className="text-sm font-semibold text-ocean-950">
              {unmapped.length} column{unmapped.length === 1 ? "" : "s"} we will ignore
            </p>
            <p className="mt-1 text-xs text-slate-500">
              Nothing here is lost from your file — it simply has no place in the
              catalogue. If one of these should be used, pick it above.
            </p>
            <p className="mt-2 text-xs text-slate-600">
              {unmapped.map(({ header }) => header).join(" · ")}
            </p>
          </div>
        )}
      </div>

      <Actions onBack={onBack} onNext={onNext} nextLabel="Continue" disabled={!canContinue} />
    </div>
  );
}

// ── Step 3: settings ───────────────────────────────────────────────────

function SettingsStep({
  settings,
  setSettings,
  categories,
  fileCategories,
  pending,
  onBack,
  onNext,
}: {
  settings: Settings;
  setSettings: (update: (s: Settings) => Settings) => void;
  categories: CategoryOption[];
  /** The categories this file creates — what the markup panel asks about. */
  fileCategories: CategoryScan[];
  pending: boolean;
  onBack: () => void;
  onNext: () => void;
}) {
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) =>
    setSettings((s) => ({ ...s, [key]: value }));

  return (
    <div className="mt-6 space-y-6">
      <section className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">Stock</h2>
        <p className="mt-1 text-sm text-slate-500">
          A supplier file is normally a delivery — what just arrived, not what
          is on the shelf. Getting this wrong is invisible until someone counts.
        </p>

        <div className="mt-4 grid gap-3 md:grid-cols-2">
          <Choice
            checked={settings.stockMode === "receive"}
            onChange={() => set("stockMode", "receive")}
            title="Receive shipment"
            description="Add these quantities to whatever is already in stock. Use this for a delivery."
          />
          <Choice
            checked={settings.stockMode === "set"}
            onChange={() => set("stockMode", "set")}
            title="Set stock"
            description="Replace current stock with these numbers. Use this for a first load or a stocktake."
          />
        </div>
      </section>

      <section className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">Categories</h2>

        <div className="mt-4 grid gap-4 md:grid-cols-2">
          <label>
            <span className="label">File everything under</span>
            <select
              className="input"
              value={settings.rootSlug}
              onChange={(event) => set("rootSlug", event.target.value)}
            >
              {categories.map((category) => (
                <option key={category.slug} value={category.slug}>
                  {"— ".repeat(category.depth)}
                  {category.name}
                </option>
              ))}
            </select>
            <span className="mt-1 block text-xs text-slate-500">
              Your file&apos;s own categories become children of this one, and
              are created if they don&apos;t exist.
            </span>
          </label>

          <Toggle
            checked={settings.mergeBasicLines}
            onChange={(value) => set("mergeBasicLines", value)}
            title={'Merge "Basic" ranges'}
            description='File "BASIC SHIRT" under Shirts rather than creating a near-duplicate category next to it.'
          />
        </div>
      </section>

      <section className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">Pricing</h2>
        <p className="mt-1 text-sm text-slate-500">
          Supplier files carry <strong>cost</strong>. Your selling price is worked
          out from it — cost is stored, and never shown to customers.
        </p>

        <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <label>
            <span className="label">Cost currency</span>
            <input
              className="input"
              value={settings.currency}
              onChange={(event) => set("currency", event.target.value.toUpperCase().slice(0, 4))}
            />
          </label>
          <label>
            <span className="label">Rate to store currency</span>
            <input
              className="input"
              type="number"
              min="0.0001"
              step="0.0001"
              value={settings.fxRate}
              onChange={(event) => set("fxRate", Number(event.target.value) || 1)}
            />
          </label>
          <label>
            <span className="label">Default markup</span>
            <input
              className="input"
              type="number"
              min="1"
              step="0.1"
              value={settings.defaultMarkup}
              onChange={(event) => set("defaultMarkup", Number(event.target.value) || 1)}
            />
          </label>
          <label>
            <span className="label">Round prices to</span>
            <select
              className="input"
              value={settings.rounding}
              onChange={(event) => set("rounding", event.target.value as RoundingMode)}
            >
              <option value="ends-99">….99</option>
              <option value="ends-90">….90</option>
              <option value="whole">Whole numbers</option>
              <option value="none">Exact</option>
            </select>
          </label>
        </div>

        {/*
          The categories in THIS file, not a fixed list.

          A kitchenware seller was previously asked to price shirts, suits,
          socks and bow-ties — sixteen menswear categories left over from
          the file this importer was first written against — while Vacuum
          Flasks and Lunch Boxes, which their file actually creates, were
          absent and quietly took the global default.
        */}
        {fileCategories.length > 0 && (
          <details className="mt-4 rounded-xl bg-sand-50 p-4">
            <summary className="cursor-pointer text-sm font-semibold text-ocean-950">
              Markup per category ({fileCategories.length} in this file)
            </summary>
            <p className="mt-2 text-xs text-slate-500">
              One multiplier cannot suit everything in a catalogue. Any
              category left at the default above uses it.
            </p>
            <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
              {fileCategories.map((category) => (
                <label key={category.slug} className="flex items-center gap-2 text-sm">
                  <span className="min-w-0 flex-1 truncate text-slate-600" title={category.name}>
                    {category.name}
                    <span className="ml-1 text-xs text-slate-400">({category.rows})</span>
                  </span>
                  <input
                    className="input !w-20 !py-1.5 text-right"
                    type="number"
                    min="1"
                    step="0.1"
                    aria-label={`Markup for ${category.name}`}
                    value={settings.markupByCategory[category.slug] ?? settings.defaultMarkup}
                    onChange={(event) =>
                      setSettings((s) => ({
                        ...s,
                        markupByCategory: {
                          ...s.markupByCategory,
                          [category.slug]: Number(event.target.value) || 1,
                        },
                      }))
                    }
                  />
                </label>
              ))}
            </div>
          </details>
        )}

        {fileCategories.length === 0 && (
          <p className="mt-4 rounded-xl bg-sand-50 px-4 py-3 text-xs text-slate-500">
            This file has no category column mapped, so every product uses the
            default markup above and is filed under the parent category you
            picked.
          </p>
        )}
      </section>

      <section className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">
          Products that already exist
        </h2>
        <p className="mt-1 text-sm text-slate-500">
          Matched by barcode, then variant code, then product code. Stock is
          always updated — these control everything else.
        </p>

        <div className="mt-4 grid gap-3 md:grid-cols-3">
          <Toggle
            checked={settings.overwritePrices}
            onChange={(value) => set("overwritePrices", value)}
            title="Update prices"
            description="Re-price existing products with the markup above."
          />
          <Toggle
            checked={settings.overwriteDetails}
            onChange={(value) => set("overwriteDetails", value)}
            title="Overwrite names & descriptions"
            description="Off by default — this would replace any wording you have edited by hand."
          />
          <Toggle
            checked={settings.publishImmediately}
            onChange={(value) => set("publishImmediately", value)}
            title="Publish new products now"
            description="Off by default: no import can supply photos, so new products stay hidden until you add one."
          />
        </div>
      </section>

      <Actions
        onBack={onBack}
        onNext={onNext}
        nextLabel="Preview the import"
        pending={pending}
      />
    </div>
  );
}

function Choice({
  checked,
  onChange,
  title,
  description,
}: {
  checked: boolean;
  onChange: () => void;
  title: string;
  description: string;
}) {
  return (
    <label
      className={
        "cursor-pointer rounded-xl border-2 p-4 transition " +
        (checked ? "border-ocean-500 bg-ocean-50" : "border-sand-200 bg-white hover:border-ocean-200")
      }
    >
      <span className="flex items-center gap-2">
        <input type="radio" checked={checked} onChange={onChange} className="accent-ocean-600" />
        <span className="font-semibold text-ocean-950">{title}</span>
      </span>
      <span className="mt-1 block text-xs leading-relaxed text-slate-500">{description}</span>
    </label>
  );
}

function Toggle({
  checked,
  onChange,
  title,
  description,
}: {
  checked: boolean;
  onChange: (value: boolean) => void;
  title: string;
  description: string;
}) {
  return (
    <label className="cursor-pointer rounded-xl border border-sand-200 bg-white p-4">
      <span className="flex items-center gap-2">
        <input
          type="checkbox"
          checked={checked}
          onChange={(event) => onChange(event.target.checked)}
          className="accent-ocean-600"
        />
        <span className="font-semibold text-ocean-950">{title}</span>
      </span>
      <span className="mt-1 block text-xs leading-relaxed text-slate-500">{description}</span>
    </label>
  );
}

// ── Step 4: review and commit ──────────────────────────────────────────

function ReviewStep({
  preview,
  settings,
  progress,
  pending,
  onBack,
  onCommit,
}: {
  preview: PreviewPayload;
  settings: Settings;
  progress: {
    processed: number;
    total: number;
    created: number;
    updated: number;
    skipped: number;
    failed: { name: string; reason: string }[];
    categories: string[];
    done: boolean;
  } | null;
  pending: boolean;
  onBack: () => void;
  onCommit: () => void;
}) {
  const [filter, setFilter] = useState<"all" | "create" | "update" | "blocked">("all");
  const { stats } = preview;

  const shown = preview.products.filter((p) => filter === "all" || p.action === filter);
  const blocked = stats.blocked > 0;

  if (progress) {
    return (
      <ProgressPanel progress={progress} pending={pending} />
    );
  }

  return (
    <div className="mt-6 space-y-6">
      <section className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">
          What this import will do
        </h2>

        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="Rows read" value={stats.rows.toLocaleString()} />
          <Stat
            label="Sellable units"
            value={stats.units.toLocaleString()}
            note={
              stats.mergedRows > 0
                ? `${stats.mergedRows.toLocaleString()} duplicate lines added together`
                : undefined
            }
          />
          <Stat label="Products" value={stats.products.toLocaleString()} />
          <Stat label="Units of stock" value={stats.totalQty.toLocaleString()} />
        </div>

        <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="New products" value={String(stats.create)} tone="good" />
          <Stat label="Existing updated" value={String(stats.update)} />
          <Stat label="Blocked" value={String(stats.blocked)} tone={blocked ? "bad" : undefined} />
          <Stat
            label="Retail value"
            value={money(stats.retailValue)}
            note={`cost ${money(stats.totalCost)}`}
          />
        </div>

        {stats.mergedRows > 0 && (
          <p className="mt-4 rounded-xl bg-ocean-50 px-4 py-3 text-sm text-ocean-900">
            {stats.mergedRows.toLocaleString()} rows repeated a barcode already
            listed elsewhere in the file. Their quantities were{" "}
            <strong>added together</strong> rather than overwriting each other —
            this is normal for a purchase invoice.
          </p>
        )}

        <p className="mt-4 text-sm text-slate-600">
          Stock mode:{" "}
          <strong>
            {settings.stockMode === "receive"
              ? "receive — quantities are added to existing stock"
              : "set — existing stock is replaced by these quantities"}
          </strong>
          . New products will be{" "}
          <strong>{settings.publishImmediately ? "published immediately" : "hidden until you add photos"}</strong>.
        </p>
      </section>

      {(preview.newCategories.length > 0 || preview.existingCategories.length > 0) && (
        <section className="card p-6">
          <h2 className="font-display text-lg font-bold text-ocean-950">Categories</h2>
          <div className="mt-3 flex flex-wrap gap-2">
            {preview.newCategories.map((category) => (
              <span
                key={category.slug}
                className="rounded-full bg-mango-100 px-3 py-1 text-sm text-mango-800"
              >
                + {category.name} ({category.count})
              </span>
            ))}
            {preview.existingCategories.map((category) => (
              <span
                key={category.slug}
                className="rounded-full bg-sand-100 px-3 py-1 text-sm text-slate-600"
              >
                {category.name} ({category.count})
              </span>
            ))}
          </div>
          {preview.newCategories.length > 0 && (
            <p className="mt-3 text-xs text-slate-500">
              Categories in mango will be created under{" "}
              <strong>{settings.rootSlug}</strong>.
            </p>
          )}
        </section>
      )}

      {preview.issues.length > 0 && (
        <IssuePanel preview={preview} />
      )}

      <section className="card overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-sand-200 p-4">
          <h2 className="font-display text-lg font-bold text-ocean-950">
            Products ({shown.length})
          </h2>
          <div className="flex flex-wrap gap-2 text-sm">
            {(["all", "create", "update", "blocked"] as const).map((option) => (
              <button
                key={option}
                type="button"
                onClick={() => setFilter(option)}
                className={
                  "rounded-full px-3 py-1 capitalize transition " +
                  (filter === option
                    ? "bg-ocean-700 text-white"
                    : "bg-sand-100 text-slate-600 hover:bg-sand-200")
                }
              >
                {option}
              </button>
            ))}
          </div>
        </div>

        <div className="max-h-[32rem] overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="sticky top-0 bg-sand-50 text-xs uppercase tracking-wide text-slate-500">
              <tr>
                <th className="px-4 py-3">Product</th>
                <th className="px-4 py-3">Category</th>
                <th className="px-4 py-3 text-right">Variants</th>
                <th className="px-4 py-3 text-right">Stock</th>
                <th className="px-4 py-3 text-right">Cost</th>
                <th className="px-4 py-3 text-right">Price</th>
                <th className="px-4 py-3 text-right">Margin</th>
              </tr>
            </thead>
            <tbody>
              {shown.map((product) => (
                <ProductRow key={product.itemCode} product={product} mode={settings.stockMode} />
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <button type="button" onClick={onBack} className="btn-secondary !px-5 !py-2 text-sm">
          Back to settings
        </button>
        <button
          type="button"
          onClick={onCommit}
          disabled={pending || stats.create + stats.update === 0}
          className="btn-primary !px-6 !py-3 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {pending
            ? "Importing…"
            : `Import ${(stats.create + stats.update).toLocaleString()} products`}
        </button>
      </div>
    </div>
  );
}

function ProductRow({ product, mode }: { product: PreviewProduct; mode: StockMode }) {
  const [open, setOpen] = useState(false);

  const tone =
    product.action === "create"
      ? "bg-ocean-100 text-ocean-800"
      : product.action === "update"
        ? "bg-sand-100 text-slate-600"
        : "bg-coral-100 text-coral-700";

  return (
    <>
      <tr
        className="cursor-pointer border-t border-sand-100 align-top hover:bg-sand-50"
        onClick={() => setOpen((value) => !value)}
      >
        <td className="px-4 py-3">
          <div className="flex items-start gap-2">
            <span className={"mt-0.5 rounded-full px-2 py-0.5 text-[11px] font-bold uppercase " + tone}>
              {product.action}
            </span>
            <div className="min-w-0">
              <p className="truncate font-medium text-ocean-950">{product.name}</p>
              <p className="text-xs text-slate-400">{product.itemCode}</p>
              {product.matchedName && product.matchedName !== product.name && (
                <p className="text-xs text-slate-500">→ {product.matchedName}</p>
              )}
            </div>
          </div>
        </td>
        <td className="px-4 py-3 text-slate-600">
          {product.category ?? "—"}
          {product.subcategory && (
            <span className="block text-xs text-slate-400">{product.subcategory}</span>
          )}
        </td>
        <td className="px-4 py-3 text-right text-slate-600">{product.variantCount}</td>
        <td className="px-4 py-3 text-right text-slate-600">
          {/* Show the sum only when it IS the sum. A product whose stock was
              held flat rather than on variants does not carry over, and
              printing "20 +263 = 263" would read as a bug. */}
          {product.previousStock !== undefined &&
          mode === "receive" &&
          product.previousStock + product.qty === product.newStock ? (
            <span>
              {product.previousStock} <span className="text-slate-400">+{product.qty}</span> ={" "}
              <strong>{product.newStock}</strong>
            </span>
          ) : product.previousStock !== undefined ? (
            <span>
              <span className="text-slate-400">{product.previousStock} →</span>{" "}
              <strong>{product.newStock}</strong>
            </span>
          ) : (
            <strong>{product.newStock}</strong>
          )}
        </td>
        <td className="px-4 py-3 text-right text-slate-500">{money(product.cost)}</td>
        <td className="px-4 py-3 text-right font-semibold text-ocean-950">
          {money(product.price)}
        </td>
        <td className="px-4 py-3 text-right text-slate-600">{product.margin}%</td>
      </tr>

      {open && (
        <tr className="border-t border-sand-100 bg-sand-50/60">
          <td colSpan={7} className="px-4 py-3">
            <div className="grid gap-3 md:grid-cols-3">
              <Detail label="Colours" value={product.colors.join(" · ") || "—"} />
              <Detail label="Sizes" value={product.sizes.join(" · ") || "—"} />
              <Detail label="Example barcode" value={product.sampleBarcode ?? "none"} />
            </div>
            {product.issues.length > 0 && (
              <ul className="mt-3 space-y-1 text-xs text-coral-700">
                {product.issues.map((issue, index) => (
                  <li key={index}>⚠ {issue}</li>
                ))}
              </ul>
            )}
          </td>
        </tr>
      )}
    </>
  );
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p>
      <p className="mt-0.5 text-sm text-slate-700">{value}</p>
    </div>
  );
}

function IssuePanel({ preview }: { preview: PreviewPayload }) {
  const [open, setOpen] = useState(preview.issueCounts.error > 0);

  // Same sentence repeated 85 times teaches nothing the first one didn't.
  const grouped = useMemo(() => {
    const byCode = new Map<string, { level: string; count: number; example: string }>();
    for (const issue of preview.issues) {
      const entry = byCode.get(issue.code);
      if (entry) entry.count++;
      else byCode.set(issue.code, { level: issue.level, count: 1, example: issue.message });
    }
    const rank = { error: 0, warning: 1, info: 2 } as Record<string, number>;
    return [...byCode.entries()].sort((a, b) => rank[a[1].level] - rank[b[1].level]);
  }, [preview.issues]);

  const { error, warning, info } = preview.issueCounts;

  return (
    <section className="card p-6">
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        className="flex w-full items-center justify-between gap-3 text-left"
      >
        <h2 className="font-display text-lg font-bold text-ocean-950">
          Checks
          <span className="ml-3 text-sm font-normal text-slate-500">
            {error > 0 && <span className="text-coral-700">{error} blocking</span>}
            {error > 0 && (warning > 0 || info > 0) && " · "}
            {warning > 0 && <span className="text-mango-700">{warning} warnings</span>}
            {warning > 0 && info > 0 && " · "}
            {info > 0 && <span>{info} notes</span>}
          </span>
        </h2>
        <span className="text-slate-400">{open ? "▲" : "▼"}</span>
      </button>

      {open && (
        <ul className="mt-4 space-y-2 text-sm">
          {grouped.map(([code, entry]) => (
            <li
              key={code}
              className={
                "rounded-xl px-4 py-3 " +
                (entry.level === "error"
                  ? "bg-coral-100 text-coral-700"
                  : entry.level === "warning"
                    ? "bg-mango-50 text-mango-800"
                    : "bg-sand-50 text-slate-600")
              }
            >
              <span className="font-semibold">{entry.count}×</span> {entry.example}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function ProgressPanel({
  progress,
  pending,
}: {
  progress: {
    processed: number;
    total: number;
    created: number;
    updated: number;
    skipped: number;
    failed: { name: string; reason: string }[];
    categories: string[];
    done: boolean;
  };
  pending: boolean;
}) {
  const percent = progress.total > 0 ? Math.round((progress.processed / progress.total) * 100) : 0;

  return (
    <div className="mt-6 space-y-6">
      <section className="card p-6">
        <h2 className="font-display text-lg font-bold text-ocean-950">
          {progress.done ? "Import finished" : "Importing…"}
        </h2>

        <div className="mt-4 h-3 overflow-hidden rounded-full bg-sand-100">
          <div
            className="h-full rounded-full bg-ocean-500 transition-all"
            style={{ width: `${percent}%` }}
          />
        </div>
        <p className="mt-2 text-sm text-slate-500">
          {progress.processed.toLocaleString()} of {progress.total.toLocaleString()} products
          {pending && !progress.done && " — keep this page open"}
        </p>

        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="Created" value={String(progress.created)} tone="good" />
          <Stat label="Updated" value={String(progress.updated)} />
          <Stat label="Skipped" value={String(progress.skipped)} />
          <Stat
            label="Failed"
            value={String(progress.failed.length)}
            tone={progress.failed.length > 0 ? "bad" : undefined}
          />
        </div>

        {progress.categories.length > 0 && (
          <p className="mt-4 text-sm text-slate-600">
            Categories created: {progress.categories.join(", ")}
          </p>
        )}

        {progress.failed.length > 0 && (
          <div className="mt-4">
            <p className="text-sm font-semibold text-coral-700">
              These products were not written — everything else was:
            </p>
            <ul className="mt-2 max-h-56 space-y-1 overflow-auto text-xs text-slate-600">
              {progress.failed.map((failure, index) => (
                <li key={index} className="rounded-lg bg-coral-100/50 px-3 py-2">
                  <strong>{failure.name}</strong> — {failure.reason}
                </li>
              ))}
            </ul>
          </div>
        )}

        {progress.done && (
          <div className="mt-6 flex flex-wrap gap-3">
            <Link href="/vendor/products" className="btn-primary !px-5 !py-2 text-sm">
              View my products
            </Link>
            <Link href="/vendor/photos" className="btn-secondary !px-5 !py-2 text-sm">
              Add photos
            </Link>
          </div>
        )}
      </section>
    </div>
  );
}

function Stat({
  label,
  value,
  note,
  tone,
}: {
  label: string;
  value: string;
  note?: string;
  tone?: "good" | "bad";
}) {
  return (
    <div
      className={
        "rounded-xl p-4 " +
        (tone === "good" ? "bg-ocean-50" : tone === "bad" ? "bg-coral-100/60" : "bg-sand-50")
      }
    >
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-1 font-display text-2xl font-extrabold text-ocean-950">{value}</p>
      {note && <p className="mt-0.5 text-xs text-slate-500">{note}</p>}
    </div>
  );
}
